name: PlatCode Backend

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./plate-server
          push: true
          tags: |
            ghcr.io/whatnext-id/plate-code-detector:latest
            ghcr.io/whatnext-id/plate-code-detector:${{ github.sha }}

      - name: Deploy
        run: |
          set -euxo pipefail

          mkdir -p ~/.ssh

          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=yes \
            -i ~/.ssh/id_ed25519 \
            "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" << 'EOF'

          set -euxo pipefail

          echo "Connected to server"
          whoami
          hostname

          cd ~/PlateCode/plate-server

          docker compose pull
          docker compose up -d

          docker image prune -f

          docker compose ps

          EOF
