name: PlatCode Backend (Golang)

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
        shell: bash

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful!'"
        shell: bash

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          if [ ! -d ~/PlateCode ]; then
            git clone https://github.com/WhatNext-ID/plate-code-detector ~/PlateCode
          fi
          cd ~/PlateCode
          git pull origin main
          cd plate-server
          docker compose down --remove-orphans
          docker compose --project-name plate-code up --build -d
          docker image prune -a -f
          EOF
